title: Minwoo's Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://kmu.minwoo.blog
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: kmu-Minwoo
  email: alsdn4956@kookmin.ac.kr
  linkedin: 

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
